name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # клонируем репу на github actions

      - name: Set up Python
        uses: actions/setup-python@v4 # устанавливаем нужную версию python
        with:
          python-version: '3.10' # версия, которую установим

      - name: Install dependencies # команды для установки библиотек
        run: |
          python -m pip install --upgrade pip  
          pip install fastapi uvicorn pytest pytest-html requests

      - name: Start FastAPI Server # команды для запуска сервера(фоновый запуск, затем ожидание)
        run: |
          nohup uvicorn main:app --port 3000 -reload &
          sleep 15

      - name: Run tests # команды для запуска тестов
        run: |
          pytest -v -s test_api.py

      - name: Upload Test Report # команды для сохранения отчета о тесте
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
