name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # клонируем репу на github actions

      - name: Set up Python
        uses: actions/setup-python@v3 # устанавливаем нужную версию python
        with:
          python-version: '3.10' # версия, которую установим

      - name: Install dependencies # команды для установки библиотек
        run: |
          python -m pip install --upgrade pip  
          pip install fastapi uvicorn pytest pytest-html requests

      - name: Start FastAPI Server # команды для запуска сервера(фоновый запуск, затем ожидание)
        run: |
          nohup uvicorn main:app --port 3000 --reload &
          sleep 5  

      - name: Run tests # команды для запуска тестов
        run: |
          pytest --html=report.html --self-contained-html

      - name: Generate Allure Report # генерация отчета в allure
        run: |
          allure generate allure-results -o allure-report --clean
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Test Report # команды для сохранения отчета о тесте
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
