name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-html requests

      - name: Start FastAPI Server
        run: |
          nohup uvicorn main:app --port 3000 --reload &
          sleep 5  # даем время серверу запуститься

      - name: Run tests
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
