name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-html requests

      - name: Start FastAPI Server
        run: |
          nohup uvicorn main:app --port 3000 --reload &
    # Ждем, пока сервер не станет доступен, максимум 30 секунд
          for i in {1..30}; do
            if curl --fail http://127.0.0.1:3000/glucose; then
            echo "Server is up!"
            exit 0
          fi
            echo "Waiting for server..."
              sleep 1
          done
          echo "Server did not start in time."
          exit 1


      - name: Run tests
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
